### ISSUE TITLE
Breaks the page

### ISSUE THREAD

**Issue by silvi** [VidFerris/TickTickStylesheet#1]
Hello, I just came upon your custom stylesheet, which looks extremely nice in pics, but seems to be broken on my side.

I am using it with Stylus + 80% Zoom and it seems to break the page, things get cut out and others plain don't work.

Perhaps Ticktick got updated? Is this script still being worked on?

Thanks!

**Comment by john-streit** [comment]
> Hello, I just came upon your custom stylesheet, which looks extremely nice in pics, but seems to be broken on my side.
> 
> I am using it with Stylus + 80% Zoom and it seems to break the page, things get cut out and others plain don't work.
> 
> Perhaps Ticktick got updated? Is this script still being worked on?
> 
> Thanks!

Hello, it looks like we both need the same thing.  I'm not a CSS developer, but I'm persistent.  Please look this over and maybe we can get a solution in place.
TickTick COMPACT VIEW - please create a via a CSS file tweak.  See https://github.com/VidFerris/TickTickStylesheet/issues/2

**Comment by VidFerris** [comment]
Hi Silvi; sorry for the delayed response. I've updated the stylesheet and it works on the current TickTick version on my end, so if you're still interested feel free to try it out.
