### ISSUE TITLE
TickTick COMPACT VIEW  - please create via a CSS file tweak

### ISSUE THREAD

**Issue by john-streit** [VidFerris/TickTickStylesheet#2]
https://github.com/VidFerris/TickTickStylesheet  - custom CSS by VidFerris from April 2020 using tools he recommended.
Requesting a simple COMPACT TickTick Task-View using a CSS tweak in Chrome for an Inbox at about 2x the density.  There’s too much whitespace when users have long lists, and scrolling is 4x slower when trying to categorize or move tasks to lists At least 30 people requested this from TickTick for the past 4 years, but they never implemented it yet.  I’m assuming that this will only take a SME less than an hour to do one of these options, but many users will thank you.

•	A. Could someone please create a basic TickTick COMPACT VIEW  via a CSS file tweak?  
•	B. Or do a quickstep-by-step with snapshots for how to do this using the recommended tools.
•	Attached are some snapshots showing roughly the JS and Style sections that I think need tweaking.
•	If you go to the Inbox view JS comment “Loading View Start” this is where it creates the Task-table.  Then look at the corresponding CSS on the right pane.  I believe it’s trial & error in debug to reduce the Margins, Borders, Padding, row height, fonts, etc.
•	Use Chrome Extensions  like Stylus  + Tampermonkey   (add-ons which apply custom stylesheets.)
•	https://userstyles.org/styles/139980/darkshay-ticktick  - nice but too much stuff breaks.

Snapshots of JS and CSS sections where task table is built.
[TT-TickTickDebug-Inbox-TopTasks.docx](https://github.com/VidFerris/TickTickStylesheet/files/6282696/TT-TickTickDebug-Inbox-TopTasks.docx)

**Comment by john-streit** [comment]
"Want to throw money at me in thanks?  you can do this at https://ko-fi.com/randomini no pressure tho"
I saw this in your new REadme, but wasn't able to find where/how to make a payment to you.  What is appropriate?
I will direct other TickTick users here too who have been asking for View Tweak like Inbox.

**Comment by VidFerris** [comment]
Hi John; my stylesheet increases the font size so that it takes up a larger percentage of the height of a task. If you want the sizes of the tasks to be smaller, you can just zoom out on the page in your browser. There's a lot of other Javascript components of the page that are dependent on task height being that specific value so doing it this way is easier. I updated the stylesheets this morning with various fixes (my local version and this one have been out of sync for a while); I hope you find it useful.
